### ISSUE TITLE
USER STORY: Navigation bar

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#1]
As a **logged-in user**, I can **view a navbar from every page** so that **I can navigate easily between pages**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a navigation bar;
- Acceptance Criteria2: Include links to navigate the website;
- Acceptance Criteria3: All links must function properly.

## Tasks:
- [ ] Task1: Create the NavBar component
- [ ] Task2: Import it in App.js;
- [ ] Task3: Create links for the NavBar;
- [ ] Task4: Create and wire up a NavBar.module.css file for styling the component if needed.
