### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#10]
As a **logged-in user**, I can **edit my profile** so that **I can change my profile picture, interests, and bio**.

## Acceptance Criteria:
- Acceptance Criteria1: Add an edit profile form;
- Acceptance Criteria2: When the user submits the form with valid data, it updates the profile.
- Acceptance Criteria3: If a user is not the profile owner, they can't access the form.

## Tasks:
- [x] Task1: Create the ProfileEdit form;
- [x] Task2: Wire up the form in App.js;
- [x] Task3: Request the profile data to the API and send back the updated data.
- [x] Task4: Create and wire up the ProfileEditForm.module.css file to style the component if needed.
