### ISSUE TITLE
USER STORY: Follow/Unfollow a user

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#11]
As a **logged-in user**, I can **follow and unfollow other users** so that **I can see and remove events by specific users in my events feed**.

## Acceptance Criteria:
- Acceptance Criteria1:  Create a Follow button to allow the user to follow a profile;
- Acceptance Criteria2: Clicking the button, the number of people the user is following and the number of people that the user is being followed by will increase by one;
- Acceptance Criteria3:  Clicking the Follow button, the text should change to Unfollow;
- Acceptance Criteria4: Clicking the Unfollow button, the number of people that the user is being followed by and the number of people the user is following will decrease by one;

## Tasks:
- [x] Tasks1: Define HandleFollow and HandleUnfollow functions;
- [x] Tasks2: The Handle Follow should send  to the API information about what profile the user just followed, increase the followed user followed_count, and increase the following user the following_count;
- [x] Tasks3: The Handle Unfollow should delete the following id previously created, decrease the followed user followed_count, and decrease the following user following_count.
