### ISSUE TITLE
USER STORY: <Manage comment>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#14]
As a **comment owner**, I can **edit and delete my comment** so that **I can make corrections after my comment was created**.

## Acceptance Criteria:
- Acceptance Criteria1: Add an Edit Comment form;
- Acceptance Criteria2: When the event owner submits the form with valid data, it updates the comment;
- Acceptance Criteria3: When the event owner clicks the delete button, it deletes the comment and decreases the number of comments by one;
- Acceptance Criteria4: If a user is not the event owner, they can't access the form.

## Tasks:
- [ ] Task1: Create the Edit Comment form;
- [ ] Task2: Wire up the form in Comment.js;
- [ ] Task3: Request the comment data to the API and send back the updated data;
- [ ] Task4: If the action is deletion, send the delete command to the API for the comment data to be deleted;
- [ ] Task5: If the action is deletion, decrease the comments count by one;
- [ ] Task6: Wire up the CommentCreateEditForm.module.css file for styling the component.
