### ISSUE TITLE
USER STORY: <Create comments>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#16]
As a **logged-in user**, I can **add comments to an event** so that **I can share my thoughts about the event**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a Create Comment form;
- Acceptance Criteria2: When the user submits the form with valid data, it creates a new comment.
- Acceptance Criteria3: When a new comment is created, the number of comments displayed next to the comment icon increases by one.

## Tasks:
- [ ] Task1: Create a Comment Create form;
- [ ] Task2: Wire up the form in EventPage.js;
- [ ] Task3: Send the data to the API to store it in the database;
- [ ] Task4: Increase the comments count by one;
- [ ] Task5: Create and wire up a CommentCreateEditForm.module.css file for styling if needed.
