### ISSUE TITLE
USER STORY: View genres list

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#2]
As an **admin**, I can **view the genres list** so that **I can see which new genres I can add**.

## Acceptance Criteria:
- Acceptance Criteria1: Show all genres by category.

## Tasks:
- [ ] Task1: Create a Genre component;
- [ ] Task2: Wire up the Genre component in Category Page;
- [ ] Task3: Fetch the genres data from the API, filtered by category;
- [ ] Task4: Create and wire up a Genre.module.css file for styling the component if needed.
