### ISSUE TITLE
USER STORY: <View the events list>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#22]
As a **user**, I can **view the events ordered from the farthest in the future.** so that **I can view the events in chronological order**.

## Acceptance Criteria:
- Acceptance Criteria1: Show all the events;
- Acceptance Criteria2: Display the events in chronological order from the farthest in the future to the oldest.

## Tasks:
- [ ] Task1: Add an Events page;
- [ ] Task2: Wire up the page in App.js;
- [ ] Task3: Fetch the Events data from the API;
- [ ] Task4: Create and wire up a EventsPage.module.css file for styling if needed.
