### ISSUE TITLE
USER STORY: Manage event

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#26]
As an **event owner**, I can **edit and delete my event** so that **I can make corrections or update my event after it was created**.

## Acceptance Criteria:
- Acceptance Criteria1: Add an Edit Event form;
- Acceptance Criteria2: When the event owner submits the form with valid data, it updates the event;
- Acceptance Criteria3: When the event owner clicks the delete button, it deletes the event;
- Acceptance Criteria4: If a user is not the event owner, they can't access the form.

## Tasks:
- [x] Task1: Create the Edit Event form;
- [x] Task2: Wire up the form in App.js;
- [x] Task3: Request the event data to the API and send back the updated data;
- [x] Task4: If the action is deletion,  send the delete command to the API for the event data to be deleted;
- [x] Task5: Wire up the EventCreateEditForm.module.css file for styling the component if needed.
