### ISSUE TITLE
USER STORY: View event

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#27]
As a **logged-in user** , I can **view the details of an event** so that **I can learn more about it**.

## Acceptance Criteria:
- Acceptance Criteria1:  As a user clicks on an Event, it should open the respective Event page;
- Acceptance Criteria2: The Event page should display all Event's details.

## Tasks:
- [x] Task1: Create an event page;
- [x] Task2: Wire up the event page in App.js;
- [x] Task3: In the event page file, fetch the data about the post;
- [x] Task4: Display the fetched data.
- [x] Task5: Create and wire up a EventPage.module.css file for styling the component if needed.
