### ISSUE TITLE
USER STORY: <Create an event>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#28]
As a **logged-in user**, I can **create events** so that **other users with my same interests can participate**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a Create Event form;
- Acceptance Criteria2:  When the user submits the form with valid data, it creates a new event.

## Tasks:
- [ ] Task1: Create a Create Event form;
- [ ] Task2: Wire up the form in App.js
- [ ] Task3: Send the data to the API to store it in the database;
- [ ] Task4: Create and wire up a EventCreateEditForm.module.css file for styling the component if needed.
