### ISSUE TITLE
USER STORY: <Log into the account>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#30]
As a **user**, I can **sign in to the app** so that **I can access functionality for logged-in users**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a sign-in form;
- Acceptance Criteria2: If the user doesn't fill up the form correctly, it should display an error message relative to the issue; 
- Acceptance Criteria3: Once the user is signed in, they should be able to access restricted functionality.

## Tasks:
- [ ] Task1: Create a sign-in form;
- [ ] Task2: Import the form in App.js;
- [ ] Task3: Send the details to the API to validate the log-in;
- [ ] Task4: Wire up the SignInUpForm.module.css file for styling the component if needed.
