### ISSUE TITLE
USER STORY: <Account registration>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#31]
As a **user**, I can **create a new account** so that **I can access all the features for signed-up users**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a sign-up form;
- Acceptance Criteria2: The sign-up form should request the user to type the password twice;
- Acceptance Criteria3: The details inserted in the sign-up form must work for the user sign-in.

## Tasks:
- [ ] Task1: Create a sign-up form;
- [ ] Task2: Wire up the form in App.js
- [ ] Task3: Send the data to the API to store it in the database;
- [ ] Task4: Create and wire up a SignInUpForm.module.css file for styling the component if needed.
