### ISSUE TITLE
USER STORY: Add photos

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#32]
As a **logged-in user**, I can **post photos of the event** so that **users can have a visual insight into the event**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a Create Photo form;
- Acceptance Criteria2:  When the user submits the form with valid data, it creates a new Photo.

## Tasks:
- [ ] Task1: Create a Create Photo form;
- [ ] Task2: Wire up the form on the event page;
- [ ] Task3: Send the data to the API to store it in the database;
- [ ] Task4: Create and wire up a PhotoCreateEditForm.module.css file for styling the component if needed.
