### ISSUE TITLE
USER STORY: Manage photos

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#33]
As a **photo owner**, I can **edit and delete my photos** so that **I can make corrections after the photo was posted**.

## Acceptance Criteria:
- Acceptance Criteria1: Add an Edit Photo form;
- Acceptance Criteria2:  When the user submits the form with valid data, it updates the previous Photo.

## Tasks:
- [x] Task1: Create an Edit Photo form;
- [x] Task2: Wire up the form on the photo page;
- [x] Task3: Send the data to the API to update the photo details in the database;
- [x] Task4: Wire up a PhotoCreateEditForm.module.css file for styling the component if needed.
