### ISSUE TITLE
USER STORY: View the photo list

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#34]
As a **logged-in user**, I can **view a photo list of the event** so that **I can have a better understanding of the event**.

## Acceptance Criteria:
- Acceptance Criteria1:  Show all photos of the event.
- Acceptance Criteria2: Display the photos in chronological order from the most recent to the oldest.

## Tasks:
- [ ] Task1: Create a Gallery Page;
- [ ] Task2: Wire up the component on the event page;
- [ ] Task3: Fetch the photos data from the API filtered by event;
- [ ] Task4: Create and wire up a GalleryPage.module.css file for styling the component if needed.
