### ISSUE TITLE
USER STORY: Manage genres

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#4]
As an **admin**, I can **edit and delete a genre** so that **I can make corrections or update the category after it was created**.

## Acceptance Criteria:
- Acceptance Criteria1: Add an Edit Genre form;
- Acceptance Criteria2: When the admin submits the form with valid data, it updates the genre;
- Acceptance Criteria3: When the admin clicks the delete button, it deletes the genre;
- Acceptance Criteria4: If a user is not the admin, they can't access the form.

## Tasks:
- [x] Task1: Create the Edit Genre form;
- [x] Task2: Wire up the form in the Category Page;
- [x] Task3: Request the genre data to the API and send back the updated data;
- [x] Task4: If the action is deletion, send the delete command to the API for genre data to be deleted;
- [x] Task5: Wire up the GenreCreateEditForm.module.css file for styling the component if needed.
