### ISSUE TITLE
USER STORY: <Manage categories>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#5]
As an **admin**, I can **edit and delete a category** so that **I can make corrections or update the category after it was created**.

## Acceptance Criteria:
- Acceptance Criteria1: Add an Edit Category form;
- Acceptance Criteria2: When the admin submits the form with valid data, it updates the category;
- Acceptance Criteria3: When the admin clicks the delete button, it deletes the event;
- Acceptance Criteria4: If a user is not the admin, they can't access the form.

## Tasks:
- [ ] Task1: Create the Edit Category form;
- [ ] Task2: Wire up the form in the Category Page;
- [ ] Task3: Request the category data to the API and send back the updated data;
- [ ] Task4: If the action is deletion, send the delete command to the API for category data to be deleted;
- [ ] Task5: Wire up the CategoryCreateEditForm.module.css file for styling the component if needed.
