### ISSUE TITLE
USER STORY: <Create Genres>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#6]
As an **admin**, I can **create genres** so that **users can add genres to the event they create and add them to their preferences**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a Create Genre form;
- Acceptance Criteria2:  When the admin submits the form with valid data, it creates a new genre.

## Tasks:
- [ ] Task1: Create a Create Genre form;
- [ ] Task2: Wire up the form in the Category Page;
- [ ] Task3: Send the data to the API to store it in the database;
- [ ] Task4: Create a security system so that only the admin can access the form;
- [ ] Task5: Create and wire up a GenreCreateEditForm.module.css file for styling the component if needed.
