### ISSUE TITLE
USER STORY: <Create Categories>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#7]
As an **admin**, I can **create categories** so that **other users can add a category to the event they create**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a Create Category form;
- Acceptance Criteria2:  When the admin submits the form with valid data, it creates a new category.

## Tasks:
- [ ] Task1: Create a Create Category form;
- [ ] Task2: Wire up the form in Categories Page;
- [ ] Task3: Send the data to the API to store it in the database;
- [ ] Task4: Create a security system so that only the admin can access the form;
- [ ] Task5: Create and wire up a CategoryCreateEditForm.module.css file for styling the component if needed.
