### ISSUE TITLE
USER STORY: <Update username and password>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/onlyevents87#9]
As a **logged-in user**, I can **update my username and password** so that **I can change my display name and keep my profile secure**.

## Acceptance Criteria:
- Acceptance Criteria1:  Create a username form and a password form;
- Acceptance Criteria2: When the form is submitted, it should update the relevant data;
- Acceptance Criteria3: If the user is not the profile owner, they shouldn't access the forms.

## Tasks:
- [ ] Task1: Add a UsernameForm and UserPasswordForm;
- [ ] Task2: Wire them up in App.js;
- [ ] Task3: The forms should update the username and the password, respectively.
